name: call-build.yml
on: 
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      app_name: "Web-app"
      environment: "production"
    secrets: 
      docker_token: ${{ secrets.DOCKERHUB_TOKEN }}

  display-version:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Display Build Version
        run: |
           echo "Build version is: ${{ needs.build.outputs.build_version }}"
   
  
