name: Complete Workflow
on:
  push: 
env:
 APP_NAME: myapp

jobs:
  test:
   runs-on: ubuntu-latest
   env:
       Environment: stagging

   steps:
     - name: Print Environment Variables and GitHub Context
       env:
        VERSION: 1.0.0
       run: |
          echo "APP_NAME: $APP_NAME"
          echo "ENVIRONMENT: $ENVIRONMENT"
          echo "VERSION: $VERSION"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
        
   
