name: To print Hello from GitHub Actions!

on:
  push:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run a simple script
        run: echo "Hello from GitHub Actions!"
      - name: To current date and time
        run: echo "The current date and time is $(date +%T)"
      - name: Print branch name
        run: echo "The branch is ${{ github.ref_name}}"
      - name: List the files in the repo
        run:  git ls-files
      - name: Print the runner's operating system
        shell: bash
        run: |
         echo  "$RUNNER_OS"
        
        
