name: Multi-OS Workflow
on:
  push

jobs:
  linux-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v7
      - name: Run linux command
        run: echo "This job runs on Ubuntu"
      - name: Print OS Name via Environment Variable
        run: echo "The Operating system is $Runner_OS"
  windows-job:
      runs-on: windows-latest
      steps:
        - name: Checkout the code
          uses: actions/checkout@v7
        - name: Run windows command
          run: Write-Output "This job runs on Windows"
        - name: Print OS Name via Environment Variable
          run: echo "The Operating system is $Runner_OS"
  macos-jobs:
      runs-on: macos-latest
      steps:
        - name: Checkout the code 
          uses: actions/checkout@v7
        - name: Run macos command
          run: echo "This job runs on macOS"
        - name: Print OS Name via Environmet Varibale
          run: echo "The Operating system is $Runner_OS"
