name: PR_Checks

on:
  pull_request:
    branches:
      - main

jobs:
  file-size-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check modified file sizes
        run: |
          # Get list of added or modified files in the PR
          files=$(git diff --name-only --diff-filter=ACMRT origin/${{ github.base_ref }}...HEAD)

          failed=0

          for file in $files; do
            if [ -f "$file" ]; then
              size=$(stat -c%s "$file")

              # 1 MB = 1048576 bytes
              if [ "$size" -gt 1048576 ]; then
                echo "Error: $file is larger than 1 MB ($size bytes)."
                failed=1
              fi
            fi
          done

          exit $failed
