name: Reusable Build

on:
  workflow_call:
    inputs:
      app_name:
        description: "This is the app for testing purpose"
        required: true
        type: string

      environment:
        description: "Target deployment environment"
        required: true
        default: "staging"
        type: string

    secrets:
      docker_token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Display Inputs
        run: |
          echo "Deploying ${{ inputs.app_name }}"
          echo "Target environment is ${{ inputs.environment }}"

      - name: Check Docker Token Status
        run: |
          if [ -n "${{ secrets.docker_token }}" ]; then
            echo "Docker token is set: true"
          else
            echo "Docker token is missing or empty."
          fi
