name: Reusable Build

on:
  workflow_call:
    inputs:
      app_name:
        description: "This is the app for testing purpose"
        required: true
        type: string

      environment:
        description: "Target deployment environment"
        required: true
        default: "staging"
        type: string

    secrets:
      docker_token:
        required: true

    outputs:
      build_version:
        description: "Generated build version"
        value: ${{ jobs.build.outputs.build_version }}

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      build_version: ${{ steps.version.outputs.build_version }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Display Inputs
        run: |
          echo "Deploying ${{ inputs.app_name }}"
          echo "Target environment is ${{ inputs.environment }}"

      - name: Generate Build Version
        id: version
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          BUILD_VERSION="v1.0-${SHORT_SHA}"
          echo "Build version: $BUILD_VERSION"
          echo "build_version=$BUILD_VERSION" >> "$GITHUB_OUTPUT"

      - name: Check Docker Token Status
        run: |
          if [ -n "${{ secrets.docker_token }}" ]; then
            echo "Docker token is set: true"
          else
            echo "Docker token is missing or empty."
          fi
