name: smart-triggers

on:
  pull_request:
    branches:
      - release

jobs:
  smart-triggers:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Release PR triggered successfully"
