name: smart-triggers

on:
  pull_request:

jobs:
  smart-triggers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Print message
        run: echo "Workflow triggered successfully"
